# ===============LICENSE_START=======================================================
# Acumos Apache-2.0
# ===================================================================================
# Copyright (C) 2017-2018 AT&T Intellectual Property & Tech Mahindra. All rights reserved.
# ===================================================================================
# This Acumos software file is distributed by AT&T and Tech Mahindra
# under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ===============LICENSE_END=========================================================
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
 name: acumos
 namespace: ${ACUMOS_NAMESPACE}
 labels:
   app: acumos
spec:
 selector:
   matchLabels:
     app: acumos
     tier: frontend
 replicas: 1
 template:
   metadata:
     labels:
       app: acumos
       tier: frontend
   spec:
     containers:
       - name: onboarding-app
         image: ${NEXUS3_RELEASE_REGISTRY_LF}/${ACUMOS_ONBOARDING_IMAGE}
         ports:
           - containerPort: ${ACUMOS_ONBOARDING_APP_PORT}
         env:
           - name: SPRING_APPLICATION_JSON
             value: '{ "server" :{ 
                   "port" : ${ACUMOS_ONBOARDING_APP_PORT} 
                 },
                 "docker" : { 
                            "host" : "${ACUMOS_DOCKER_HOST}.${ACUMOS_NAMESPACE}",
                            "port": ${ACUMOS_DOCKER_PORT} ,
                            "config": "/docker_host/.docker",
                            "registry" :{"url": "http://${ACUMOS_NEXUS_SERVICE}.${ACUMOS_NAMESPACE}:${ACUMOS_NEXUS_PORT}/",
                            "username" : "${ACUMOS_NEXUS_USERNAME}",
                            "password" : "${ACUMOS_NEXUS_PASSWORD}", 
                            "email": "${ACUMOS_DOCKER_REGISTRY_EMAIL}"},
                            "tls": { "verify": "false" }, 
                            "api": { "version": "1.23" },
                            "imagetag":{
                                "prefix": "${ACUMOS_NEXUS_SERVICE}.${ACUMOS_NAMESPACE}:${ACUMOS_NEXUS_PORT}" 
                                    },
                            "max_total_connections":  "1", "max_per_route_connections": "1" 
                            },
                 "http_proxy": "http://${ACUMOS_PROXY}.${ACUMOS_NAMESPACE}:${ACUMOS_PROXY_PORT}",
                 "nexus": {
                            "nexusEndPointURL": "http://${ACUMOS_NEXUS_SERVICE}.${ACUMOS_NAMESPACE}:${ACUMOS_NEXUS_ENDPOINT_PORT}/repository/acumos-k8-models-maven/",
                            "nexusUserName": "${ACUMOS_NEXUS_USERNAME}",
                            "nexusPassword": "${ACUMOS_NEXUS_PASSWORD}",
                            "nexusproxy": "",
                            "nexusGroupId": "com.artifact" 
                           },
                 "cmndatasvc": {
                                "cmnDataSvcEndPoinURL": "http://acumos.${ACUMOS_NAMESPACE}:${ACUMOS_COMMON_DATA_SVC_PORT}/ccds",
                                "cmnDataSvcUser": "${ACUMOS_CDS_USER}",
                                "cmnDataSvcPwd": "${ACUMOS_CDS_PASSWORD}" 
                               },
                 "tosca": {
                            "OutputFolder" : "/temp/",
                            "GeneratorEndPointURL": "http://acumos.acumos-ns01:8080/model_create" 
                          },
                 "mktPlace": {
                              "mktPlaceEndPoinURL" : "http://acumos.${ACUMOS_NAMESPACE}:${ACUMOS_PORTAL_BE_PORT}"  
                              },
                 "requirements": { 
                                  "extraIndexURL": "",
                                  "trustedHost": "" 
                                 }, 
                 "authenticationServiceURL": "http://acumos.${ACUMOS_NAMESPACE}:${ACUMOS_PORTAL_BE_PORT}" 
                 }'
       - name: acumos-portal-be
         image: ${NEXUS3_RELEASE_REGISTRY_LF}/${ACUMOS_PORTAL_BE_IMAGE}
         ports:
           - containerPort: ${ACUMOS_PORTAL_BE_PORT}
         env:
           - name: SPRING_APPLICATION_JSON
             value: '{ "server" : {
                   "port" : ${ACUMOS_PORTAL_BE_PORT}
                },
                "nexus": {
                        "url": "http://${ACUMOS_NEXUS_SERVICE}.${ACUMOS_NAMESPACE}:${ACUMOS_NEXUS_ENDPOINT_PORT}/repository/acumos-k8-models-maven",
                        "proxy": "",
                        "password": "${ACUMOS_NEXUS_PASSWORD}",
                        "username": "${ACUMOS_NEXUS_USERNAME}",
                        "groupid": "com.artifact"
                },
                "cdms" : {
                  "client" : {
                     "url": "http://acumos.${ACUMOS_NAMESPACE}:${ACUMOS_COMMON_DATA_SVC_PORT}/ccds",
                     "username": "${ACUMOS_CDS_USER}",
                     "password": "${ACUMOS_CDS_PASSWORD}"
                     }
                },
                "docker" : {
                   "host" : "${ACUMOS_DOCKER_HOST}.${ACUMOS_NAMESPACE}",
                   "resgistry" : {
                      "url": "http://${ACUMOS_NEXUS_SERVICE}.${ACUMOS_NAMESPACE}:${ACUMOS_NEXUS_PORT}/",
                      "username" : "${ACUMOS_NEXUS_USERNAME}",
                      "password" : "${ACUMOS_NEXUS_PASSWORD}",
                      "email": "admin@acumos.com"
                   },
                   "imagetag" : {
                       "prefix": "${ACUMOS_NEXUS_SERVICE}.${ACUMOS_NAMESPACE}:${ACUMOS_NEXUS_PORT}"
                   }
                },
                "qanda" : {
                   "url" : "https://${ACUMOS_QANDA_URL}"
                },
                "onboarding" : {
                   "push" : {
                       "model" : {
                          "url" : "http://acumos.${ACUMOS_NAMESPACE}:${ACUMOS_ONBOARDING_APP_PORT}/onboarding-app/v2/models",
			  "dcae_url" : "http://acumos.${ACUMOS_NAMESPACE}:${ACUMOS_ONBOARDING_APP_PORT}/onboarding-app/v2/dcae_models"
                       }
                   }
                },
                "model" : {
                   "storage" : {
                      "folder" : {
                         "name" : "/acumosWebOnboarding"
                      }
                   }
                },
                "doc" : {
                   "url" : "https://wiki.acumos.org"
                },
                "portal" : {
                   "mailjet" : {
                      "api" : {
                         "key" : "${ACUMOS_MAILJET_API_KEY}"
                      },
                      "secret" : {
                         "key" : "${ACUMOS_MAILJET_SECRET_KEY}"
                      },
                      "address" : {
                         "from" : "${ACUMOS_MAILJET_ID}"
                      }
                   },
                   "feature" : {
                      "validateModel" : "false",
                      "email_service" : "mailjet",
                      "cas_enabled" : "false"
                   },
                   "submitValidation" : {
                       "api" : "http://acumos.${ACUMOS_NAMESPACE}:${ACUMOS_VALIDATION_PORT}/status/v1.0/tasks"
                   },
                   "dashboard":{
                       "url" : "http://acumos.${ACUMOS_NAMESPACE}:${ACUMOS_KIBANA_PORT}"
                   }
                },
                "client" : {
                   "ssl" : {
                      "key-store" : "/app/certs/acumos_ist.pkcs12",
                      "key-store-password" : "${ACUMOS_KEY_STORE_PWD}",
                      "key-store-type" : "PKCS12",
                      "key-password" : "${ACUMOS_KEY_STORE_PWD}",
                      "trust-store" : "/app/certs/acumosTrustStore.jks",
                      "trust-store-password" : "${ACUMOS_TRUST_STORE_PWD}"
                   }
                 },
                 "gateway" : {
                    "url" : "https://acumos.acumos-ns01:9884"
                 },
                 "dcae" : {
                    "model" : {
                       "name" : {
                          "prefix" : "ONAP"
                       }
                    }
                },
                 "cas"  : {
                    "service" : {
                       "validate" : {
                            "url"  : "https://identity.linuxfooundation.org/cas/serviceValidate"
                       }
                    }
                } }'
       - name: acumos
         image: ${NEXUS3_RELEASE_REGISTRY_LF}/${ACUMOS_PORTAL_FE_IMAGE}
         ports:
          - containerPort: ${ACUMOS_PORTAL_FE_PORT}
            name: acumos
         env:
           - name: ACUMOS_DB_HOST
             value: acumos-mysql
           - name: ACUMOS_DB_PASSWORD
             value: ${ACUMOS_MARIADB_ROOT_PASSWORD}
           - name: SPRING_APPLICATION_JSON
             value: '{ "server" : {
                    "port" : ${ACUMOS_PORTAL_FE_PORT}
                },
               "zuul" : {
                   "routes" : {
                      "api" : {
                        "url": "http://acumos.${ACUMOS_NAMESPACE}:${ACUMOS_PORTAL_BE_PORT}"
                      },
                      "dsce": {
                        "url": "http://acumos.${ACUMOS_NAMESPACE}:${ACUMOS_PORTAL_DS_COMPOSITION_PORT}"
                      },
                      "site" : {
                        "url": "http://acumos.${ACUMOS_NAMESPACE}:${ACUMOS_CMS_PORT}"
                      },
                      "cmnt" : {
                         "url" : "http://acumos.${ACUMOS_NAMESPACE}:${ACUMOS_PLATON_PORT}"
                      },
                      "azure" : {
                          "url" : "http://acumos.${ACUMOS_NAMESPACE}:${ACUMOS_AZURE_CLIENT_PORT}"
                      }
                   },
                   "host" : {
                      "connect-timeout-millis" : 300000,
                      "socket-timeout-millis" : 300000
                   }
               },
               "spring" : {
                  "http" : {
                     "multipart" : {
                        "max-file-size": -1,
                        "max-request-size": -1
                     }
                  }
               }
               }'
       - name:  acumos-cms-docker
         image: ${NEXUS3_RELEASE_REGISTRY_LF}/${ACUMOS_CMS_IMAGE}
         ports:
          - containerPort: ${ACUMOS_CMS_PORT}
         env:
           - name: SPRING_APPLICATION_JSON
             value: '{ "server" : {
                    "port" : ${ACUMOS_CMS_PORT}
                },
                "spring" : {
                    "datasource" : {
                        "url" : "jdbc:mysql://acumos-mysql:${ACUMOS_MARIADB_PORT}/${ACUMOS_CMS_DB}?useSSL=false",
                        "username" : "${ACUMOS_CMS_USER}",
                        "password" : "${ACUMOS_CMS_PASSWORD}"
                  }
                },
                "parameters": {
                   "repository" : {
                      "dataSource" : {
                         "url" : "jdbc:mysql://acumos-mysql:${ACUMOS_MARIADB_PORT}/${ACUMOS_CMS_DB}?useSSL=false",
                         "username" : "${ACUMOS_CMS_USER}",
                         "password" : "${ACUMOS_CMS_PASSWORD}"
                      }
                   }
                } }'
       - name:  ds-compositionengine
         image: ${NEXUS3_RELEASE_REGISTRY_LF}/${ACUMOS_DESIGN_STUDIO_IMAGE}
         ports:
           - containerPort: ${ACUMOS_PORTAL_DS_COMPOSITION_PORT}
         env:
           - name: SPRING_APPLICATION_JSON
             value: '{ "server": {
                    "port": ${ACUMOS_PORTAL_DS_COMPOSITION_PORT} 
                    },
                    "dateformat": "yyyy-MM-dd-HH-mm-ss-SSS",
                    "lib":"/maven/",
                    "tosca": { "outputfolder": "/temp/output/" },
                "nexus": { 
                         "nexusendpointurl": "http://${ACUMOS_NEXUS_SERVICE}.${ACUMOS_NAMESPACE}:${ACUMOS_NEXUS_ENDPOINT_PORT}/repository/acumos-k8-models-maven/",
                         "nexusproxy": "",
                         "nexuspassword": "${ACUMOS_NEXUS_PASSWORD}",
                         "nexususername": "${ACUMOS_NEXUS_USERNAME}",
                         "nexusgroupid": "com.artifact" 
                         },
                "cmndatasvc": { 
                              "cmndatasvcendpoinurl": "http://acumos.${ACUMOS_NAMESPACE}:${ACUMOS_COMMON_DATA_SVC_PORT}/ccds",
                              "cmndatasvcuser": "${ACUMOS_CDS_USER}",
			                  "cmndatasvcpwd": "${ACUMOS_CDS_PASSWORD}" 
                              },
				"imagedatabrokerURI":"${NEXUS3_STAGING_REGISTRY_LF}/${ACUMOS_DATA_BROKER_IMAGE}",
                "csvdatabrokerURI":"${NEXUS3_STAGING_REGISTRY_LF}/${ACUMOS_CSV_DATA_BROKER_IMAGE}",
                "jsondatabrokerURI": "NA",
                "sqldatabrokerURI": "NA",
                "docker": {
                           "host": "${ACUMOS_DOCKER_HOST}.${ACUMOS_NAMESPACE}",
                           "port": ${ACUMOS_DOCKER_PORT},
                           "config": "/docker_host/.docker",
                           "registry": {
                                        "url": "http://${ACUMOS_NEXUS_SERVICE}.${ACUMOS_NAMESPACE}:${ACUMOS_NEXUS_PORT}/",
                                        "username": "${ACUMOS_NEXUS_USERNAME}",
                                        "password": "${ACUMOS_NEXUS_PASSWORD}",
                                        "email": "${ACUMOS_DOCKER_REGISTRY_EMAIL}"
                                            },
                            "tls": {"verify": "false"},
                            "api": {"version": "1.23"},
                            "imagetag": {
                                        "prefix": "${ACUMOS_NEXUS_SERVICE}.${ACUMOS_NAMESPACE}:${ACUMOS_NEXUS_PORT}"
                                            },
                            "max_total_connections": "1",
                            "max_per_route_connections": "1"
                            } }'
       - name:  common-data-svc
         image: ${NEXUS3_RELEASE_REGISTRY_LF}/${ACUMOS_CDS_IMAGE}
         ports:
           - containerPort: ${ACUMOS_COMMON_DATA_SVC_PORT}
         env:
           - name: SPRING_APPLICATION_JSON
             value: '{ "server" : { 
                 "port" : ${ACUMOS_COMMON_DATA_SVC_PORT} },
                 "security" : {
                             "user" : {
                                      "name": "${ACUMOS_CDS_USER}", 
                                      "password": "${ACUMOS_CDS_PASSWORD}"
                                      }
                             },
                "spring" : { 
                           "database" : { 
                                      "driver" : { "classname" : "org.mariadb.jdbc.Driver"} 
                                        },
                            "datasource" : {
                                        "url" : "jdbc:mysql://acumos-mysql:${ACUMOS_MARIADB_PORT}/${ACUMOS_CDS_DB}?useSSL=false",
                                        "username" : "${ACUMOS_MARIADB_USER}",
                                        "password" : "${ACUMOS_MARIADB_PASSWORD}"
                                        },
                            "jpa" : {
                                    "database-platform" : "org.hibernate.dialect.MySQLDialect",
                                     "hibernate" : { 
                                            "ddl-auto" : "validate" 
                                             }
                                     } 
                             }
                     }'
       - name:  federation-gateway
         image: ${NEXUS3_RELEASE_REGISTRY_LF}/${ACUMOS_FEDERATION_IMAGE}
         ports:
           - containerPort: ${ACUMOS_FEDERATION_GATEWAY_PORT}
         env:
           - name: SPRING_APPLICATION_JSON
             value: '{ "federation" : {
               "instance" : "gateway",
               "instance.name" : "k8",
               "operator" : "d468656f-57d0-46e3-9f94-7ffa4f66dc03",
               "address" : "0.0.0.0",
               "server" : {
                 "port" : ${ACUMOS_FEDERATION_GATEWAY_PORT}
               },
               "ssl" : {
                 "key-store" : "/app/certs/acumos_ist2.pkcs12",
                 "key-store-password" : "${ACUMOS_KEY_STORE_PWD}",
                 "key-store-type" : "PKCS12",
                 "key-password" : "${ACUMOS_KEY_STORE_PWD}",
                 "trust-store" : "/app/certs/acumosTrustStore.jks",
                 "trust-store-password" : "${ACUMOS_TRUST_STORE_PWD}"
               }
             },
             "local" : {
               "address": "0.0.0.0",
               "server": {
                 "port" : 9884
               },
               "ssl" : {
                 "key-store" : "/app/certs/acumos_ist2.pkcs12",
                 "key-store-password" : "ACUMOS_KEY_STORE_PWD",
                 "key-store-type" : "PKCS12",
                 "key-password" : "ACUMOS_KEY_STORE_PWD",
                 "trust-store" : "/app/certs/acumosTrustStore.jks",
                 "trust-store-password" : "${ACUMOS_TRUST_STORE_PWD}"
               }
             },
             "nexus": {
               "nexusendpointurl": "http://${ACUMOS_NEXUS_SERVICE}.${ACUMOS_NAMESPACE}:${ACUMOS_NEXUS_ENDPOINT_PORT}/repository/acumos-k8-models-maven/",
               "nexusproxy": "",
               "nexuspassword": "${ACUMOS_NEXUS_PASSWORD}",
               "nexususername": "${ACUMOS_NEXUS_USERNAME}",
               "nexusgroupid": "com.artifact"
             },
             "peer": {
               "jobchecker": {
                 "interval": 300
               }
             },
             "cdms" : {
               "client" : {
                 "url": "http://acumos.${ACUMOS_NAMESPACE}:${ACUMOS_COMMON_DATA_SVC_PORT}/ccds",
                 "username": "${ACUMOS_CDS_USER}",
                 "password": "${ACUMOS_CDS_PASSWORD}"
               }
             }}'
         volumeMounts:
           - name: acumos-persistent-storage
             mountPath: /var/www/html
     volumes:
       - name: acumos-persistent-storage
         persistentVolumeClaim:
           claimName: acumos-volumeclaim
     imagePullSecrets:
       - name: acumossecret