apiVersion: apps/v1
# ===============LICENSE_START=======================================================
# Acumos Apache-2.0
# ===================================================================================
# Copyright (C) 2017-2019 AT&T Intellectual Property & Tech Mahindra. All rights reserved.
# ===================================================================================
# This Acumos software file is distributed by AT&T and Tech Mahindra
# under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ===============LICENSE_END=========================================================
#
# What this is: deployment template for the AIO k8s deployer tool, when run
# in the target k8s cluster as a pod.

kind: Deployment
metadata:
  namespace: <ACUMOS_NAMESPACE>
  name: aio-k8s-deployer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aio-k8s-deployer
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: aio-k8s-deployer
    spec:
      securityContext:
        runAsUser: 0
        fsGroup: 1000
      containers:
      - name: aio-k8s-deployer
        image: <AIO_K8S_DEPLOYER_IMAGE>
        command: ['/bin/bash', '-c']
        args:
        - while true; do sleep 3600; done;
