# ===============LICENSE_START=======================================================
# Acumos Apache-2.0
# ===================================================================================
# Copyright (C) 2018-2019 AT&T Intellectual Property & Tech Mahindra. All rights reserved.
# ===================================================================================
# This Acumos software file is distributed by AT&T and Tech Mahindra
# under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ===============LICENSE_END=========================================================

apiVersion: apps/v1
kind: Deployment
metadata:
 name: {{ .Values.global.cds.podName | quote }}
 namespace: "{{ .Values.global.namespace }}"
 labels:
   app: {{ .Values.global.cds.name | quote }}
spec:
 selector:
   matchLabels:
     app: {{ .Values.global.cds.name | quote }}
 replicas: 1
 revisionHistoryLimit: 10
 template:
   metadata:
     labels:
       app: {{ .Values.global.cds.name | quote }}
   spec:
     containers:
       - name:  cds
         image: "{{ .Values.global.image.repository }}/{{ .Values.global.acumosCdsImage }}"
         resources:
           {{- toYaml .Values.resources | nindent 10 }}
         ports:
           - containerPort: {{ .Values.global.acumosCommonDataSvcPort }}
         env:
           - name: spring_security_user_name
             valueFrom:
               secretKeyRef:
                  name: ccdsclientsecret
                  key: username
           - name: spring_security_user_password
             valueFrom:
               secretKeyRef:
                  name: ccdsclientsecret
                  key: password
           - name: SPRING_APPLICATION_JSON
             value: '{ "server": {
                 "port": "{{ .Values.global.acumosCommonDataSvcPort }}" },
                 "logging": {
                    "level": {
                        "root": "{{ .Values.logLevel }}"
                    }
                 },
                 "spring": {
                            "datasource": {
                                        "jdbc-url": "jdbc:mariadb://{{ .Values.global.acumosCdsDbService }}.{{ .Values.global.namespace }}:{{ .Values.global.acumosCdsDbPort }}/{{ .Values.global.acumosCdsDb }}?useLegacyDatetimeCode=false&useSSL=false",
                                        "username": "{{ .Values.global.acumosCdsDbUserName }}",
                                        "password": "{{ .Values.global.acumosCdsDbUserPassword }}"
                                        },
                            "jpa": {
                                    "database-platform": "org.hibernate.dialect.MariaDB102Dialect",
                                     "hibernate": {
                                            "ddl-auto": "validate"
                                             },
                                          "show-sql": "false"
                                     },
                             "security": {
                             "user": {
                                      "name": "${spring_security_user_name}",
                                      "password": "${spring_security_user_password}"
                                      }
                             }
                            }
                     }'
         volumeMounts:
           - mountPath: /maven/logs
             name: common-data-svc-logs
       - name: filebeat
         image: "{{ .Values.global.image.repository }}/{{ .Values.global.acumosFilebeatImage }}"
         ports:
           - containerPort: {{ .Values.global.acumosFilebeatPort }}
         env:
           - name: LOGSTASH_HOST
             value: "{{ .Values.global.acumosLogstashHost }}.{{ .Values.global.namespace }}"
           - name: LOGSTASH_PORT
             value: "{{ .Values.global.acumosLogstashPort }}"
         volumeMounts:
           - mountPath: /filebeat-logs
             name: common-data-svc-logs
     volumes:
       - name: common-data-svc-logs
         emptyDir: {}
     {{ if .Values.global.image.pullSecrets -}}
     imagePullSecrets:
       - name: {{ .Values.global.image.pullSecrets }}
     {{- end }}
