# Default values for elasticsearch.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
appVersion: "1.0.0"

kibana:
  image:
    repository: "nexus3.acumos.org:10004/acumos-kibana"
    tag: "2.2.2"
    pullPolicy: "IfNotPresent"
  tls:
    crt: 
    key: 
  ingress:
    enabled: false
    host: ""
    whitelist:
      enabled: false
      ranges: ""
    letsencrypt:
      enabled: false
  initResources: 
    limits:
      cpu: "0.25"
      memory: "128Mi"
    requests:
      cpu: "0.1"
      memory: "128Mi"
  resources:
    limits:
      cpu: "1.0"
      memory: "512Mi"
    requests:
      cpu: "0.25"
      memory: "512Mi"

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi