apiVersion: v1
kind: Secret
metadata:
  name: ccdsclientsecret
  namespace: "{{ .Values.global.namespace }}"
type: Opaque
data:
  username: {{ b64enc "ccds_client" }}
  {{ if (.Values.global.acumosCdsPassword) and  eq .Values.global.acumosCdsPassword "ccds_client" }}
  password: {{ b64enc "ccds_client" }}
  {{ else if ne .Values.global.acumosCdsPassword "ccds_client" }}
  password: {{ b64enc (randAlphaNum 8) }}
  {{ end }}