apiVersion: v1
kind: Secret
metadata:
  name: conditionalsecurity
  namespace: withhelm
type: Opaque
data:
  {{ if (.Values.global.acumosCdsUser) }}
  username: {{ b64enc (.Values.global.acumosCdsUser) }}
  {{ else }}
  username: {{ b64enc "ccds_client" }}
  {{ end }}
  {{ if (.Values.global.acumosCdsPassword) }}
  password: {{ b64enc (.Values.global.acumosCdsPassword) }}
  {{ else }}
  password: {{ b64enc (randAlphaNum 8) }}
  {{ end }}
