proxy:
  secretToken: "aaac18441c577955ac5e129a7161fffc581967e4d2f988c750871c6aaa93bdbb"
hub:
  extraConfig: |
    c.Spawner.cmd = ['jupyter-labhub']
#    c.KubeSpawner.profile_list = [
#        {
#            "display_name": "Minimal environment",
#            "kubespawner_override": {
#                "image": "jupyter/minimal-notebook:latest"
#            }
#        }, {
#            "display_name": "R environment",
#            "kubespawner_override": {
#                "image": "jupyter/r-notebook:latest"
#            }
#            "display_name": "Scipy environment",
#            "kubespawner_override": {
#                "image": "jupyter/scipy-notebook:latest"
#            }
#        }, {
#            "display_name": "Tensorflow environment",
#            "kubespawner_override": {
#            }
#        }, {
#            "display_name": "Datascience environment",
#            "kubespawner_override": {
#                "image": "jupyter/datascience-notebook:latest"
#            }
#        }, {
#            "display_name": "Pyspark environment",
#            "kubespawner_override": {
#                "image": "jupyter/pyspark-notebook:latest"
#            }
#        }, {
#            "display_name": "All-spark environment",
#            "kubespawner_override": {
#                "image": "jupyter/all-spark-notebook:latest"
#            }
#        }
#    ]
singleuser:
  extraEnv:
    ACUMOS_ONBOARDING_TOKENMODE: jwtToken
    ACUMOS_ONBOARDING_CLIPUSHURL: "http://onboarding-service:8090/onboarding-app/v2/models"
    ACUMOS_ONBOARDING_CLIAUTHURL: "http://onboarding-service:8090/onboarding-app/v2/auth"
  defaultUrl: "/lab"
  storage:
    type: none
  image:
    name: jupyter/tensorflow-notebook
    tag: latest
  profileList:
    - display_name: "Minimal environment"
      description: "To avoid too many bells and whistles: Python."
      kubespawner_override:
        name: jupyter/minimal-notebook:latest
    - display_name: "R environment"
      description: "Includes popular packages from the R ecosystem"
      kubespawner_override:
        image: jupyter/r-notebook:latest
    - display_name: "Scipy environment"
      description: "Includes popular packages from the scientific Python ecosystem"
      kubespawner_override:
        image: jupyter/scipy-notebook:latest
    - display_name: "Tensorflow environment"
      description: "Includes popular Python deep learning libraries"
      default: true
      kubespawner_override:
        image: jupyter/tensorflow-notebook:latest
    - display_name: "Datascience environment"
      description: "Includes libraries for data analysis from the Julia, Python, and R communities."
      kubespawner_override:
        image: jupyter/datascience-notebook:latest
    - display_name: "Pyspark environment"
      description: "Includes Python support for Apache Spark, optionally on Mesos"
      kubespawner_override:
        image: jupyter/pyspark-notebook:latest
    - display_name: "All-spark environment"
      description: "Includes Python, R, and Scala support for Apache Spark, optionally on Mesos"
      kubespawner_override:
        image: jupyter/all-spark-notebook:latest
