#============LICENSE_START=======================================================
#
#================================================================================
# Copyright (C) 2020 AT&T Intellectual Property.  All rights reserved.
#================================================================================
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ============LICENSE_END=========================================================
apiVersion: v1
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.global.acumosSoajsDataService }}"
  namespace: "{{ .Values.global.namespace }}"
  labels:
    app: "{{ .Values.global.acumosSoajsDataService }}"
    service.image.ts: "1587740803682"
    soajs.catalog.id: 5df3ec10fa3912534948f003
    soajs.catalog.v: "1"
    soajs.content: "true"
    soajs.env.code: dashboard
    soajs.resource.id: 5bed928f29f0041bf64bf989
    soajs.service.group: soajs-db
    soajs.service.label: dashboard-soajsdata
    soajs.service.mode: deployment
    soajs.service.name: soajsdata
    soajs.service.replicas: "1"
    soajs.service.subtype: mongo
    soajs.service.type: cluster
    soajs.service.version: "1"
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: "{{ .Values.global.acumosSoajsDataService }}"
  template:
    metadata:
      labels:
        app: "{{ .Values.global.acumosSoajsDataService }}"
    spec:
      containers:
      - image: "{{ .Values.global.acumosSoajsDataImage }}"
        imagePullPolicy: IfNotPresent
        name: acumos-soajsdata-container
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        ports:
        - containerPort: {{ .Values.global.acumosSoajsDataServicePort }}
          name: mongoport
        volumeMounts:
        - mountPath: /data/db
          name: dashboard-soajsdata
        - mountPath: /docker-entrypoint-initdb.d
          name: initscript
        - mountPath: /initial-data
          name: initdata
        readinessProbe:
          exec:
            command:
            - mongo
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 2
          failureThreshold: 3
      volumes:
      - name: dashboard-soajsdata
        persistentVolumeClaim:
          claimName: acumos-soajsdata-volumeclaim
      - name: initscript
        configMap:
          name: soajsdata-initscript-configmap
          defaultMode: 0755
          items:
          - key: load-data.sh
            path: load-data.sh
      - name: initdata
        configMap:
          name: soajs-initialdata-configmap
