# ===============LICENSE_START=======================================================
# Acumos Apache-2.0
# ===================================================================================
# Copyright (C) 2017-2018 AT&T Intellectual Property & Tech Mahindra. All rights reserved.
# ===================================================================================
# This Acumos software file is distributed by AT&T and Tech Mahindra
# under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ===============LICENSE_END=========================================================

# Name: nginx-manifest.yaml - nginx manifest

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus-proxy-nginx
  labels:
    app: nexus-proxy-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexus-proxy-nginx
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nexus-proxy-nginx
    spec:
      containers:
      - name: nexus-proxy-nginx
        image: nginx:stable
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1000m"
        ports:
        - containerPort: 8443
        command: ["/bin/bash", "-c"]
        args:
        - set -x;
          cp /etc/nginx/conf.d/nginx.conf /etc/nginx/nginx.conf;
          echo 'Acumos authentication proxy started';
          nginx -g "daemon off;"
        volumeMounts:
        - mountPath: /etc/nginx/conf.d
          name: conf-volume
        - mountPath: /var/log/acumos
          name: logs
      restartPolicy: Always
      volumes:
      - name: logs
        persistentVolumeClaim:
         claimName: nexus-proxy-nginx-logs
      - name: conf-volume
        configMap:
          name: nexus-proxy-nginx

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus-proxy-nginx-logs
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard

---
apiVersion: v1
kind: Service
metadata:
  name: nexus-proxy
spec:
  selector:
    app: nexus-proxy-nginx
  ports:
    - name: https-acumos-nexus
      port: 8443
      targetPort: 8443

---
apiVersion: k8s.nginx.org/v1alpha1
kind: TransportServer
metadata:
  name: nexus-proxy
spec:
  listener:
    name: tls-passthrough
    protocol: TLS_PASSTHROUGH
  host: nexus-proxy
  upstreams:
    - name: nexus-proxy
      service: acumos-nexus
      port: 8443
  action:
    pass: nexus-proxy

---
apiVersion: v1
kind: Service
metadata:
  name: nexus-pyauth
spec:
  selector:
    app: pyauth
  ports:
    - name: http-nexus-pyauth
      port: 8080
      targetPort: 8080

