apiVersion: apps/v1
# ===============LICENSE_START=======================================================
# Acumos Apache-2.0
# ===================================================================================
# Copyright (C) 2017-2018 AT&T Intellectual Property & Tech Mahindra. All rights reserved.
# ===================================================================================
# This Acumos software file is distributed by AT&T and Tech Mahindra
# under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ===============LICENSE_END=========================================================

# What this is: kubernetes template for Acumos portal-be deployment
# How to use:

kind: Deployment
metadata:
  namespace: acumos
  name: portal-be
  labels:
    app: portal-be
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portal-be
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: portal-be
    spec:
      imagePullSecrets:
      - name: acumos-registry
      containers:
      - name: portal-be
        image: nexus3.acumos.org:10004/acumos-portal-be:2.2.10
        env:
        - name: SPRING_APPLICATION_JSON
          value: '{
                    "server": {
                      "port": 8083,
                      "contextPath": "/"
                    },
                    "docker": {
                      "host": "docker-dind-service",
                      "port": "2375",
                      "registry": {
                        "url": "http://:30882/",
                        "username": "acumos_rw",
                        "password": "",
                        "email": "acumos@example.com"
                      },
                      "imagetag": {
                        "prefix": "nexus:30882"
                      }
                    },
                    "nexus": {
                      "url": "http://:30881/repository/acumos_model_maven/",
                      "proxy": "",
                      "password": "",
                      "username": "acumos_rw",
                      "groupid": "com.artifact"
                    },
                    "cdms": {
                      "client": {
                        "url": "http://cds-service:8000/ccds",
                        "username": "ccds_client",
                        "password": ""
                      }
                    },
                    "qanda": {
                      "url": "https://stackoverflow.com"
                    },
                    "doc": {
                      "url": "https://wiki.acumos.org"
                    },
                    "onboarding": {
                      "push": {
                        "model": {
                          "url": "http://onboarding-service:8090/onboarding-app/v2/models",
                          "dcae_url": "http://onboarding-service:8090/onboarding-app/v2/dcae_models"
                        }
                      },
                      "cliPushUrl": "https://:30443/onboarding-app/v2/models",
                      "cliAuthUrl": "https://:30443/onboarding-app/v2/auth",
                      "tokenmode": "jwtToken"
                    },
                    "model": {
                      "storage": {
                        "folder": {
                          "name": "/acumosWebOnboarding"
                        }
                      }
                    },
                    "portal": {
                      "feature": {
                        "publishSelfRequestEnabled": "false",
                        "validateModel": "false",
                        "email_service": "",
                        "cas_enabled": "false",
                        "download_bufferSize": 8,
                        "signup_enabled": "true",
                        "verifyAccount": "false",
                        "verifyToken": {
                          "exp_time": 24
                        },
                        "cloud_enabled": "[{\"cloudEnabled\": \"true\", \"cloudName\": \"azure\", \"cloudDisplayText\": \"Microsoft Azure\", \"imageUrl\": \"/images/deploy-cloud/microsoft_azure.png\" },{ \"cloudEnabled\": \"true\", \"cloudName\": \"rackspace\", \"cloudDisplayText\": \"Rackspace\", \"imageUrl\": \"/images/deploy-cloud/rackspace.png\" },{ \"cloudEnabled\": \"false\",  \"cloudName\": \"gcp\", \"cloudDisplayText\": \"Google Cloud Platform\", \"imageUrl\": \"/images/deploy-cloud/google_cloud_platform.png\" },{ \"cloudEnabled\": \"true\",  \"cloudName\": \"deploylocal\", \"cloudDisplayText\": \"Deploy To Local\", \"imageUrl\": \"/images/deploy-cloud/deploy_to_local.png\" },{ \"cloudEnabled\": \"false\", \"cloudName\": \"whitebox\", \"cloudDisplayText\": \"Deploy To White Box\", \"imageUrl\": \"/images/deploy-cloud/deploy_to_whitebox.png\" }]",
                        "sv": {
                          "enabled": "true",
                          "api": "http://sv-scanning-service:9082/scan"
                        }
                      },
                      "submitValidation": {
                        "api": "http://validation-client-service:9603/status/v1.0/tasks"
                      },
                      "dashboard": {
                        "url": "http://:"
                      },
                      "mailjet": {
                        "api": {
                          "key": "replace-as-needed"
                        },
                        "secret": {
                          "key": ""
                        },
                        "address": {
                          "from": "acumos@example.com"
                        }
                      },
                      "ui": {
                        "server": {
                          "address": "http://notused.com"
                        }
                      }
                    },
                    "spring": {
                      "mail" : {
                        "host" : "Provide the hostname",
                        "port" : 25,
                        "username" : "username",
                        "password" : "password",
                        "debug" : "true",
                        "smtp" : {
                          "starttls" : {
                            "enable" : "true"
                          },
                          "auth" : "false"
                        },
                        "transport" : {
                          "protocol" : "smtp"
                        },
                        "template" : {
                          "folder" : {
                            "path" : "/fmtemplates/"
                          }
                        }
                      },
                      "servlet": {
                        "multipart": {
                          "max-file-size": "1024MB",
                          "max-request-size": "1024MB"
                        }
                      }
                    },
                    "client": {
                      "ssl": {
                        "key-store": "/app/certs/acumos-keystore.p12",
                        "key-store-password": "",
                        "key-store-type": "PKCS12",
                        "key-password": "",
                        "trust-store": "/app/certs/acumos-truststore.jks",
                        "trust-store-password": ""
                      }
                    },
                    "gateway": {
                      "url": "https://:30985"
                    },
                    "dcae": {
                      "model": {
                        "name": {
                          "prefix": "ONAP"
                        }
                      }
                    },
                    "jwt": {
                      "auth": {
                        "timeout": "80000000"
                      }
                    },
                    "cas": {
                      "service": {
                        "validate": {
                          "url": "https://identity.linuxfoundation.org/cas/serviceValidate"
                        }
                      }
                    },
                    "document": {
                      "size": "100000000"
                    },
                    "jupyter" : {
                      "url" : "http:///"
                    },
                    "image": {
                      "size": "1000KB"
                    }
                  }'
        ports:
        - containerPort: 8083
        volumeMounts:
        - mountPath: /maven/logs
          name: logs
        - mountPath: /app/certs
          name: certs-volume
      restartPolicy: Always
      volumes:
      - name: logs
        persistentVolumeClaim:
          claimName: pvc-acumos-logs
      - name: certs-volume
        configMap:
          name: acumos-store
      hostAliases:
      - ip: ""
        hostnames:
        - ""
