#
#============LICENSE_START=======================================================
# Acumos Apache-2.0
#================================================================================
# Copyright (C) 2020 AT&T Intellectual Property & Tech Mahindra. All rights reserved.
#================================================================================
# This Acumos software file is distributed by AT&T and Tech Mahindra
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ============LICENSE_END=========================================================

apiVersion: apps/v1
kind: Deployment
metadata:
 name: {{ .Values.mlwb.predictorService.podName | quote }}
 namespace: "{{ .Values.mlwb.namespace }}"
 labels:
   app: {{ .Values.mlwb.predictorService.name | quote }}
spec:
 selector:
   matchLabels:
     app: {{ .Values.mlwb.predictorService.name | quote }}
 replicas: 1
 revisionHistoryLimit: 10
 template:
   metadata:
     labels:
       app: {{ .Values.mlwb.predictorService.name | quote }}
   spec:
     containers:
       - name: predictor-service
         image: {{ .Values.global.nexus3ReleaseRegistryLf }}/acumos/{{ .Values.mlwb.acumosPredictorServiceImage }}
         ports:
           - containerPort: {{ .Values.mlwb.acumosPredictorServicePort }}
         env:
           - name: SPRING_APPLICATION_JSON
             value: '{
                "server":{
                    "port":"{{ .Values.mlwb.acumosPredictorServicePort }}"
                },
                "dateformat": "yyyy-MM-dd-HH-mm-ss-SSS",
                "resultsetSize": "2000",
                "cmndatasvc" : {
                    "url":"http://{{ .Values.global.cds.svcName }}.{{ .Values.global.namespace }}:{{ .Values.global.acumosCommonDataSvcPort }}/ccds",
                    "user":"{{ .Values.global.acumosCdsUser }}",
                    "pwd":"{{ .Values.global.acumosCdsPassword }}"
                },
                "couchdb":{
                    "user":"{{ .Values.mlwb.acumosCouchDB.user }}",
                    "pwd":"{{ .Values.mlwb.acumosCouchDB.pwd }}",
                    "name":"{{ .Values.mlwb.acumosCouchDB.dbname }}",
                    "createdb":{
                        "if-not-exist":"{{ .Values.mlwb.acumosCouchDB.createdb }}"
                    },
                    "protocol":"{{ .Values.mlwb.acumosCouchDB.protocol }}",
                    "host":"{{ .Values.mlwb.acumosCouchDB.host }}",
                    "port":"{{ .Values.mlwb.acumosCouchDB.port }}"
                },
                "projectservice": {
                    "url": "http://{{ .Values.mlwb.projectService.svcName }}.{{ .Values.global.namespace }}:{{ .Values.mlwb.acumosProjectServicePort }}/mlWorkbench/v1/project"
                },
                "modelservice": {
                    "url": "http://{{ .Values.mlwb.modelService.svcName }}.{{ .Values.global.namespace }}:{{ .Values.mlwb.acumosModelServicePort }}/mlWorkbench/v1/modelservice"
                },
                "jwt" : {
                    "secretkey":"secret"
                }}'
         volumeMounts:
           - mountPath: /maven/logs
             name: predictor-service-logs
     volumes:
       - name: predictor-service-logs
         emptyDir: {}
     imagePullSecrets:
       - name: acumossecret
