apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kibana
  namespace: "{{ .Values.namespace }}"
  labels:
    app: kibana
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        releasetime: {{ $.Release.Time }}
      labels:
        app: kibana
    spec:
      containers:
      - name: kibana
        image: "{{ .Values.kibana.image.repository}}:{{ .Values.kibana.image.tag}}"
        imagePullPolicy: {{ .Values.elasticsearch.image.pullPolicy | quote }}
        ports:
        - containerPort: 5601
        volumeMounts:
          - name: kibana
            mountPath: /usr/share/kibana/config/kibana.yml
            subPath: kibana.yml
        env:
        - name: ELASTICSEARCH_URL
          value: http://elasticsearch.{{ .Values.namespace }}:9200
      volumes:
        - name: kibana
          configMap:
            name: kibana
            items:
            - key: kibana.yml
              path: kibana.yml
      imagePullSecrets:
        - name: acumossecret		  
