apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: "{{ .Values.namespace }}"
  labels:
    app: kibana
spec:
  type: LoadBalancer
  ports:
  - name: kibana
    port: 5601
    targetPort: 5601
  selector:
    app: kibana
