apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: "{{ .Values.namespace }}"
  labels:
    app: elasticsearch
spec:
  ports:
    - name: elasticsearch
      port: 9200
      targetPort: 9200
  selector:
    app: elasticsearch
