version: '2'
# docker-compose for IST environment
# in network ilenwbvv3qnudcp0zpuj3yy0ab.bx.internal.cloudapp.net
# requires FQDN for nexus repo VM (different network)
# requires unqualified name for database VM (same network)

version: '2'
services:
   common-data-svc:
       image: ${NEXUS3_STAGING_REGISTRY_LF}/${COMMON_DATASERVICE_IMAGE}
       environment:
           SPRING_APPLICATION_JSON: '{
                "server" : {
                    "port" : 8000
                },
                "security" : {
                    "user" : {
                        "name"     : "ccds_client",
                        "password" : "ENC(CTQD7Xk5bOIuC4MaqRZtzjW1K4ArjCjr)"
                    }
                },
                "spring" : {
                    "database" : {
                        "driver" : {
                            "classname" : "org.mariadb.jdbc.Driver"
                        }
                    },
                    "datasource" : {
                        "url" : "jdbc:mysql://cognita-ist-vm01-db:3306/acumosist_1_12_0?useSSL=false",
                        "username" : "acumos_ist",
                        "password" : "ENC(TEmYTX42SMfyaoxi3RgptVxOglsJfSgt)"
                    },
                    "jpa" : {
                        "database-platform" : "org.hibernate.dialect.MySQLDialect",
                        "hibernate" : {
                            "ddl-auto" : "validate"
                        }
                   }
                 }
           }'
       expose:
           - 8000
       ports:
           - 8000:8000
       volumes:
           - cognita-logs:/maven/logs
       logging:
           driver: json-file

   onboarding-app:
       image:  ${NEXUS3_SNAPSHOT_REGISTRY_LF}/${ONBOARDING_IMAGE}
       environment:
          SPRING_APPLICATION_JSON: '{
               "server" :{
                    "port" : 8090
                },
               "docker" : {
                   "host" : "cognita-ist-vm01-core",
                   "port" : 4243,
                   "config": "/docker_host/.docker",
                   "registry" :{
                       "url": "http://cognita-nexus01.eastus.cloudapp.azure.com:8001/",
                       "username" : "cognita_model_rw",
                       "password" : "not4you",
                       "email": "admin@cognita.com"
                   },
                   "tls": {
                       "verify": "false"
                   },
                   "api": {
                       "version": "1.23"
                   },
                   "imagetag": {
                       "prefix": "cognita-nexus01.eastus.cloudapp.azure.com:8001"
                   },
                   "max_total_connections": "1",
                   "max_per_route_connections": "1"
               },
               "http_proxy": "http://10.2.0.7:3128",
               "nexus": {
                       "nexusEndPointURL": "http://cognita-nexus01.eastus.cloudapp.azure.com:8081/repository/repo_cognita_model_maven/",
                       "nexusUserName": "cognita_model_rw",
                       "nexusPassword": "not4you",
                       "nexusproxy": "",
                       "nexusGroupId": "com.artifact"
               },
               "cmndatasvc": {
                       "cmnDataSvcEndPoinURL": "http://common-data-svc:8000/ccds",
                       "cmnDataSvcUser": "ccds_client",
                       "cmnDataSvcPwd": "ccds_client"
               },
               "tosca": {
                       "OutputFolder" : "/temp/",
                       "GeneratorEndPointURL": "http://cognita-ist-vm01-core:8080/model_create"
               },
               "mktPlace": {
                    "mktPlaceEndPoinURL" : "http://cognita-ist-vm01-core:8083"
               },
               "requirements": {
                       "extraIndexURL": "http://cognita-dev1-vm01-core.eastus.cloudapp.azure.com:8087/archive",
                       "trustedHost": "cognita-dev1-vm01-core.eastus.cloudapp.azure.com"
               },
               "authenticationServiceURL": "http://cognita-ist-vm01-core:8083"
       }'
       expose:
           - 8090
       ports:
           - 8090:8090
       links:
           - common-data-svc:common-data-svc
       depends_on:
           - common-data-svc
       volumes:
           - cognita-logs:/maven/logs
           - cognita-output:/temp/
       logging:
           driver: json-file
           
   acumos-portal-be:
       image:  ${NEXUS3_SNAPSHOT_REGISTRY_LF}/${PORTAL_BE_IMAGE}
       environment:
           SPRING_APPLICATION_JSON: '{
                "server" : {
                   "port" : 8083
                },
                "nexus": {
                        "url": "http://cognita-nexus01.eastus.cloudapp.azure.com:8081/repository/repo_cognita_model_maven/",
                        "proxy": "",
                        "password": "not4you",
                        "username": "cognita_model_rw",
                        "groupid": "com.artifact"
                },
                "cdms" : {
                  "client" : {
                     "url": "http://common-data-svc:8000/ccds",
                     "username": "ccds_client",
                     "password": "ccds_client"
                     }
                },
                "qanda" : {
                   "url" : "http://cognita-ist-vm01-core:9080"
                },
                "onboarding" : {
                   "push" : {
                       "model" : {
                          "url" : "http://cognita-ist-vm01-core:8090/onboarding-app/v2/models"
                       }
                   }
                },
                "model" : {
                   "storage" : {
                      "folder" : {
                         "name" : "/acumosWebOnboarding"
                      }
                   }
                },
                "doc" : {
                   "url" : "https://wiki.acumos.org"
                },
                "portal" : {
                   "feature" : {
                      "validateModel" : "false"
                   },
                   "submitValidation" : {
                      "api" : "http://wrapper:9603/status/v1.0/tasks"
                   }
                }
           }'
       expose:
           - 8083
       ports:
           - 8083:8083
       links:
           - common-data-svc:common-data-svc
       depends_on:
           - common-data-svc
       volumes:
           - cognita-logs:/maven/logs
           - acumosWebOnboarding:/acumosWebOnboarding
       logging:
           driver: json-file
           
   acumos-portal-fe:
       image: ${NEXUS3_SNAPSHOT_REGISTRY_LF}/${PORTAL_BE_IMAGE}
       environment:
           SPRING_APPLICATION_JSON: '{
               "server" : {
                    "port" : 8085
                },
               "zuul" : {
                   "routes" : {
                      "api" : {
                        "url": "http://acumos-portal-be:8083"
                      },
                      "dsce": {
                        "url": "http://cognita-ist-vm01-core:8088"
                      },
                      "site" : {
                        "url": "http://cognita-ist-vm01-core:9080"
                      },
                      "cmnt" : {
                         "url" : "http://cognita-ist-vm01-core:9083"
                      },
                      "azure" : {
                          "url" : "http://cognita-ist-vm01-core:9081"
                      }
                   }
               },
               "spring" : {
                  "http" : {
                     "multipart" : {
                        "max-file-size": -1,
                        "max-request-size": -1
                     }
                  }
               }
           }'
       expose:
           - 8085
       ports:
           - 8085:8085
       links:
           - acumos-portal-be:acumos-portal-be
       depends_on:
           - acumos-portal-be
       volumes:
           - cognita-logs:/maven/logs
       logging:
           driver: json-file

   toscapythonserver:
       image:  ${NEXUS3_REGISTRY_AZURE}/${TOSCAPYTHON_IMAGE}
       expose:
           - 8080
       ports:
           - 8080:8080
       volumes:
           - cognita-logs:/maven/logs
       logging:
           driver: json-file

   ds-compositionengine:
       image: ${NEXUS3_SNAPSHOT_REGISTRY_LF}/${DESIGNSTUDIO_IMAGE}
       environment:
           SPRING_APPLICATION_JSON: '{
                          "server": {
                                "port": 8088
                          },
                          "dateformat": "yyyy-MM-dd-HH-mm-ss-SSS",
                          "lib":"/maven/",
                          "tosca": {
                                "outputfolder": "/temp/output/"
                          },
                          "nexus": {
                                "nexusendpointurl": "http://cognita-nexus01.eastus.cloudapp.azure.com:8081/repository/repo_cognita_model_maven/",
                                "nexusproxy": "",
                                "nexuspassword": "not4you",
                                "nexususername": "cognita_model_rw",
                                "nexusgroupid": "com.artifact"
                          },
                          "cmndatasvc": {
                                "cmndatasvcendpoinurl": "http://common-data-svc:8000/ccds",
                                "cmndatasvcuser": "ccds_client",
                                "cmndatasvcpwd": "ccds_client"
                          },
                          "docker": {
                                "host": "cognita-ist-vm01-core",
                                "port": 4243,
                                "config": "/docker_host/.docker",
                                "registry": {
                                        "url": "http://cognita-nexus01.eastus.cloudapp.azure.com:8001/",
                                        "username": "cognita_model_rw",
                                        "password": "not4you",
                                        "email": "admin@cognita.com"
                                            },
                                "tls": {"verify": "false"},
                                "api": {"version": "1.23"},
                                "imagetag": {
                                        "prefix": "cognita-nexus01.eastus.cloudapp.azure.com:8001"
                                            },
                                "max_total_connections": "1",
                                "max_per_route_connections": "1"
                            }

                        }'
       expose:
           - 8088
       ports:
           - 8088:8088
       volumes:
           - cognita-logs:/maven/logs
           - cognita-output:/temp/
       logging:
           driver: json-file
           
   acumos-platon:
       image: ${NEXUS3_REGISTRY_AZURE}/${PORTAL_PLATON_IMAGE}
       environment:
           SPRING_APPLICATION_JSON: '{
                "server" : {
                    "port" : 9083
                },
                 "spring" : {
                    "datasource" : {
                        "url" : "jdbc:mariadb://cognita-ist-vm01-db:3306/acumos_comment",
                        "username" : "CCDS_USER",
                        "password" : "CCDS_PASS"
                    },
                    "jooq" : {
                        "sql-dialect": "mariadb"
                    },
                    "platon" : {
                        "input" : {
                           "html_elements" : "h1, h2, h3, h4, h5, h6, br, p, hr, div, span, a, img, em, strong, ol, ul, li, blockquote, code, pre"
                         }
                     }
                 }
           }'
       expose:
           - 9083
       ports:
           - 9083:9083
       volumes:
           - cognita-logs:/maven/logs
       logging:
           driver: json-file

   acumos-cms-docker:
       image: ${NEXUS3_REGISTRY_AZURE}/${PORTAL_CMS_IMAGE}
       environment:
           SPRING_APPLICATION_JSON: '{
                "server" : {
                    "port" : 9080
                },
                "spring" : {
                    "datasource" : {
                        "url" : "jdbc:mysql://cognita-ist-vm01-db:3306/ACUMOS_CMS?useSSL=false",
                        "username" : "CMS_USER",
                        "password" : "CMS_PASS"
                  }
                },
                "parameters": {
                   "repository" : {
                      "dataSource" : {
                         "url" : "jdbc:mysql://cognita-ist-vm01-db:3306/ACUMOS_CMS?useSSL=false",
                         "username" : "CMS_USER",
                         "password" : "CMS_PASS"
                      }
                   }
                }
           }'
       expose:
           - 9080
       ports:
           - 9080:9080
       volumes:
           - cognita-logs:/maven/logs
       logging:
           driver: json-file
           
   federated-gateway:
       image: ${NEXUS3_SNAPSHOT_REGISTRY_LF}/${FEDERATION_IMAGE}
       environment:
           SPRING_APPLICATION_JSON: '{
               "server" : {
                    "port" : 9084,
                    "ssl" : {
                       "key-store" : "/app/certs/acumos_ist.pkcs12",
                       "key-store-password" : "acumosb",
                       "key-store-type" : "PKCS12",
                       "key-password" : "acumosb",
                       "trust-store" : "acumosTrustStore.jks",
                       "trust-store-password" : "acumos",
                       "client-auth" : "need"
                    }
                },
                "client" : {
                   "ssl" : {
                      "key-store" : "file:///app/certs/acumos_ist.pkcs12",
                      "key-store-password" : "acumosb",
                      "key-store-type" : "PKCS12",
                      "key-password" : "acumosb"
                   }
                },
                "nexus": {
                        "nexusendpointurl": "http://cognita-nexus01.eastus.cloudapp.azure.com:8081/repository/repo_cognita_model_maven/",
                        "nexusproxy": "",
                        "nexuspassword": "not4you",
                        "nexususername": "cognita_model_rw",
                        "nexusgroupid": "com.artifact"
                },
                "spring": {
                    "profiles": {
                        "active": "gateway"
                    }
                },
                "peer": {
                    "jobchecker": {
                        "interval": 300
                    }
                },
                "federated" : {
                    "instance" : "gateway",
                    "instancename": "ist",
                    "peerGatewayOperator" : "d468656f-57d0-46e3-9f94-7ffa4f66dc03"
                },
                "cdms" : {
                  "client" : {
                     "url": "http://common-data-svc:8000/ccds",
                     "username": "ccds_client",
                     "password": "ccds_client"
                  }
                }
           }'
       expose:
           - 9084
       ports:
           - 9084:9084
       links:
           - common-data-svc:common-data-svc
       depends_on:
           - common-data-svc
       volumes:
           - cognita-logs:/maven/logs
           - /home/cognitaopr/app/certs:/app/certs
       logging:
           driver: json-file

   filebeat:
       image:  ${NEXUS3_REGISTRY_AZURE}/${FILEBEAT_IMAGE}
       volumes:
           - cognita-logs:/filebeat-logs

   wrapper:
       image: ${NEXUS3_REGISTRY_AZURE}/${VALIDATION_WRAPPER_IMAGE}
       expose:
           - 9603
       ports:
           - 9603:9603
       links:
           - acumos-portal-be:acumos-portal-be

       volumes:
           - cognita-logs:/wrapper-logs
 
   intermediate:
       image: ${NEXUS3_REGISTRY_AZURE}/${VALIDATION_INTERMEDIATE_IMAGE}
       expose:
           - 9604
           - 8083
       ports:
           - 9604:9604
       links:
           - acumos-portal-be:acumos-portal-be

       volumes:
           - cognita-logs:/intermediate-logs

   root:
       image: ${NEXUS3_REGISTRY_AZURE}/${VALIDATION_ROOT_IMAGE}
       expose:
           - 9605
       ports:
           - 9605:9605

       volumes:
           - cognita-logs:/wrapper-logs

   redis:
       image: ${NEXUS3_REGISTRY_AZURE}/${REDIS_IMAGE}
       volumes:
           - cognita-logs:/redis-logs

   celery:
       image: ${NEXUS3_REGISTRY_AZURE}/${CELERY_IMAGE}
       environment:
           - C_FORCE_ROOT=true
       links:
           - redis:redis
       volumes:
           - cognita-logs:/celery-logs

   acumos-azure-client:
       image: ${NEXUS3_SNAPSHOT_REGISTRY_LF}/${AZURE_CLIENT_IMAGE}
       environment:
           SPRING_APPLICATION_JSON: '{
               "server" : {
                    "port" : 9081
                },
                "docker" : {
                    "containerNamePrefix": "cognita-e6e",
                    "host": "cognita-ist-vm01-core",
                    "port": "4243",
                    "dockerVMUserName": "dockerUser",
                    "dockerVMPassword": "12NewPA$$w0rd!",
                    "solutionPort":"8336",
                    "registry": {
                        "bluePrint": {
                            "username": "cognita_platform_ro",
                            "password": "plat1sopen"
                        },
                        "networkgroupName": "E6E-NSG",
                        "port": "80",
                        "name": "cognita-nexus01.eastus.cloudapp.azure.com:8001",
                        "url": "http://cognita-nexus01.eastus.cloudapp.azure.com:8001/",
                        "username": "cognita_model_rw",
                        "password": "not4you"
                    }
                },
                "blueprint": {
                    "ImageName": "cognita-nexus01.eastus.cloudapp.azure.com:8002/blueprint-orchestrator:1.0.0-SNAPSHOT",
                    "name": "blueprint-orchestrator"
                },
                "nexus": {
                    "url": "http://cognita-nexus01.eastus.cloudapp.azure.com:8081/repository/repo_cognita_model_maven/",
                    "nexusproxy": "",
                    "password": "not4you",
                    "username": "cognita_model_rw",
                    "groupId": "com.artifact"
                },
                "cmndatasvc": {
                    "cmndatasvcendpoinurl": "http://common-data-svc:8000/ccds",
                    "cmndatasvcuser": "ccds_client",
                    "cmndatasvcpwd": "ccds_client"
                }
           }'
       expose:
           - 9081
       ports:
           - 9081:9081
       volumes:
           - cognita-logs:/maven/logs
       logging:
           driver: json-file

# This persistent volume must be created externally:
#   docker volume create cognita-logs
#   docker volume create cognita-output
volumes:
    cognita-logs:
        external: true
    cognita-output:
        external: true
    acumosWebOnboarding:
        external: true
