# ===============LICENSE_START=======================================================
# Acumos Apache-2.0
# ===================================================================================
# Copyright (C) 2018-2020 AT&T Intellectual Property & Tech Mahindra. All rights reserved.
# ===================================================================================
# This Acumos software file is distributed by AT&T and Tech Mahindra
# under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ===============LICENSE_END=========================================================

apiVersion: apps/v1
kind: Deployment
metadata:
 name: {{ .Values.global.portal.portalFe.podName | quote }}
 namespace: "{{ .Values.global.namespace }}"
 labels:
   app: {{ .Values.global.portal.portalFe.name | quote }}
spec:
 selector:
   matchLabels:
     app: {{ .Values.global.portal.portalFe.name | quote }}
 replicas: 1
 revisionHistoryLimit: 10
 template:
   metadata:
     labels:
       app: {{ .Values.global.portal.portalFe.name | quote }}
   spec:
     containers:
       - name: acumos
         image: "{{ .Values.global.image.repository }}/{{ .Values.global.acumosPortalFeImage }}"
         resources:
           {{- toYaml .Values.resources | nindent 10 }}
         ports:
          - containerPort: {{ .Values.global.acumosPortalFePort }}
            name: acumos
         env:
           - name: SPRING_APPLICATION_JSON
             value: '{ "server": {
                    "port": "{{ .Values.global.acumosPortalFePort }}"
                },
                 "logging": {
                    "level": {
                        "root": "{{ .Values.logLevel }}"
                    }
                 },
               "qanda": {
                        "url": "https://stackoverflow.com/questions/tagged/acumos"
                    },
               "zuul": {
                   "routes": {
                      "api": {
                        "url": "http://{{ .Values.global.portal.portalBe.svcName}}.{{ .Values.global.namespace }}:{{ .Values.global.acumosPortalBePort }}"
                      },
                      "dsce": {
                        "url": "http://{{ .Values.global.namespace }}:{{ .Values.global.acumosPortalDsCompositionPort }}"
                      },
                      "cmnt": {
                         "url": "http://acumos.{{ .Values.global.namespace }}:{{ .Values.global.acumosPlatOnPort }}"
                      },
                      "workbench": {
                         "path": "/workbench/**",
                         "url": "http://{{ .Values.mlwb.homeWebcomponent.svcName }}.{{ .Values.mlwb.namespace }}:{{ .Values.mlwb.acumosHomeWebcomponentPort }}",
                         "sensitiveHeaders": ""
                      },
                      "azure": {
                          "url": "http://acumos.{{ .Values.global.namespace }}:{{ .Values.global.acumosAzureClientPort }}"
                      },
                      "openstack": {
                          "path": "/openstack/**",
                          "url": "http://acumos.{{ .Values.global.namespace }}:{{ .Values.global.acumosOpenStackClientPort }}",
                          "stripPrefix": "false",
                          "sensitiveHeaders": ""
                        },
                      "package": {
                          "path": "/package/**",
                          "url": "http://acumos.{{ .Values.global.namespace }}:{{ .Values.global.acumosKubernetesClientPort }}",
                          "stripPrefix": "true",
                          "sensitiveHeaders": ""
                        }
                   },
                   "host": {
                      "connect-timeout-millis": "300000",
                      "socket-timeout-millis": "300000"
                   }
               },
               "spring": {
                  "http": {
                     "multipart": {
                        "max-file-size": "-1",
                        "max-request-size": "-1"
                     }
                  }
               }
               }'
         volumeMounts:
           - mountPath: /maven/logs
             name: portal-fe-logs
       - name: filebeat
         image: "{{ .Values.global.image.repository }}/{{ .Values.global.acumosFilebeatImage }}"
         ports:
           - containerPort: {{ .Values.global.acumosFilebeatPort }}
         env:
           - name: LOGSTASH_HOST
             value: "{{ .Values.global.acumosLogstashHost }}.{{ .Values.global.namespace }}"
           - name: LOGSTASH_PORT
             value: "{{ .Values.global.acumosLogstashPort }}"
         volumeMounts:
           - mountPath: /filebeat-logs
             name: portal-fe-logs
     volumes:
       - name: portal-fe-logs
         emptyDir: {}
     {{ if .Values.global.image.pullSecrets -}}
     imagePullSecrets:
       - name: {{ .Values.global.image.pullSecrets }}
     {{- end }}
