# ===============LICENSE_START=======================================================
# Acumos Apache-2.0
# ===================================================================================
# Copyright (C) 2018-2020 AT&T Intellectual Property & Tech Mahindra. All rights reserved.
# ===================================================================================
# This Acumos software file is distributed by AT&T and Tech Mahindra
# under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ===============LICENSE_END=========================================================

{{ if .Values.global.ingress.enabled }}
    apiVersion: extensions/v1beta1
    kind: Ingress
    metadata:
      name: portal-fe-ingress
      namespace: "{{ .Values.global.namespace }}"
      annotations:
        {{- toYaml .Values.global.ingress.annotations | nindent 12 }}
    spec:
        rules:
        - host: {{ .Values.global.domainName }}
          http:
            paths:
            - path: /
              backend:
                serviceName: {{ .Values.global.portal.portalFe.svcName | quote }}
                servicePort: {{ .Values.global.acumosPortalFePort }}
        tls:
        - hosts:
          - {{ .Values.global.domainName }}
          secretName: {{ .Values.global.ingress.tlsSecretName }}
{{ end }}