# ===============LICENSE_START=======================================================
# Acumos Apache-2.0
# ===================================================================================
# Copyright (C) 2018-2019 AT&T Intellectual Property & Tech Mahindra. All rights reserved.
# ===================================================================================
# This Acumos software file is distributed by AT&T and Tech Mahindra
# under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ===============LICENSE_END=========================================================
#
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: config-helper
  name: config-helper
  namespace: "{{ .Values.global.namespace }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-helper
  template:
    metadata:
      labels:
        app: config-helper
    spec:
      containers:
      - name: config-helper
        image: ubuntu:latest
        imagePullPolicy: IfNotPresent
        securityContext:
            privileged: true
        command: [ '/bin/bash' ]
        args: [ '-c', 'while : ; do sleep 60 ; done' ]
        volumeMounts:
        - name: scripts-volume
          mountPath: /usr/local/bin/setup.sh
          readOnly: true
          subPath: setup.sh
        env:
        - name: K8S_NAMESPACE
          value: "{{ .Values.global.namespace }}"
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        lifecycle:
          postStart:
            exec:
              command: [ '/usr/local/bin/setup.sh' ]
      volumes:
        - name: scripts-volume
          configMap:
            defaultMode: 0700
            name: scripts
