# ===============LICENSE_START=======================================================
# Acumos Apache-2.0
# ===================================================================================
# Copyright (C) 2017-2018 AT&T Intellectual Property & Tech Mahindra. All rights reserved.
# ===================================================================================
# This Acumos software file is distributed by AT&T and Tech Mahindra
# under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ===============LICENSE_END=========================================================
apiVersion: v1
kind: Service
metadata:
  name: acumos
  namespace: ${ACUMOS_NAMESPACE}
  labels:
    app: acumos
spec:
  type: ClusterIP
  ports:
    - port: ${ACUMOS_PORTAL_FE_PORT}
      targetPort: ${ACUMOS_PORTAL_FE_PORT}
      protocol: TCP
      name: acumos
    - port: 9080
      targetPort: 9080
      protocol: TCP
      name: acumos-cms-docker
    - port: ${ACUMOS_PORTAL_BE_PORT}
      targetPort: ${ACUMOS_PORTAL_BE_PORT}
      protocol: TCP
      name: acumos-portal-be
    - port: ${ACUMOS_PORTAL_DS_COMPOSITION_PORT}
      targetPort: ${ACUMOS_PORTAL_DS_COMPOSITION_PORT}
      protocol: TCP
      name: ds-compositionengine
    - port: ${ACUMOS_COMMON_DATA_SVC_PORT}
      targetPort: ${ACUMOS_COMMON_DATA_SVC_PORT}
      protocol: TCP
      name: common-data-svc
    - port: ${ACUMOS_ONBOARDING_APP_PORT}
      targetPort: ${ACUMOS_ONBOARDING_APP_PORT}
      protocol: TCP
      name: onboarding-app
    - port: ${ACUMOS_FEDERATION_GATEWAY_PORT}
      targetPort: ${ACUMOS_FEDERATION_GATEWAY_PORT}
      protocol: TCP
      name: federation-gateway
    - port: ${ACUMOS_FEDERATION_LOCAL_PORT}
      targetPort: ${ACUMOS_FEDERATION_LOCAL_PORT}
      name: federation-local
    - port: ${ACUMOS_MICROSERVICE_GENERATION_PORT}
      targetPort: ${ACUMOS_MICROSERVICE_GENERATION_PORT}
      protocol: TCP
      name: microservice-generation  
    - port: ${ACUMOS_KUBERNETES_CLIENT_PORT}
      targetPort: ${ACUMOS_KUBERNETES_CLIENT_PORT}
      protocol: TCP
      name: kubernetes-client
    - port: ${ACUMOS_OPENSTACK_CLIENT_PORT}
      targetPort: ${ACUMOS_OPENSTACK_CLIENT_PORT}
      protocol: TCP
      name: acumos-openstack-client
    - port: 9081
      targetPort: 9081
      protocol: TCP
      name: azure-client        
  selector:
    app: acumos
    tier: frontend
