# ===============LICENSE_START=======================================================
# Acumos Apache-2.0
# ===================================================================================
# Copyright (C) 2018-2019 AT&T Intellectual Property & Tech Mahindra. All rights reserved.
# ===================================================================================
# This Acumos software file is distributed by AT&T and Tech Mahindra
# under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ===============LICENSE_END=========================================================
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: acumos-kong-deployment
  namespace: "{{ .Values.namespace }}"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: acumos-kong-deployment
        app: acumos-kong
    spec:
      containers:
      - name: acumos-kong
        image: kong:0.11.0
        env:
          - name: KONG_ADMIN_LISTEN
            value: "0.0.0.0:{{ .Values.acumosKongAdminPort }}, 0.0.0.0:{{ .Values.acumosKongAdmSslPort }} ssl"
          - name: KONG_PG_PASSWORD
            value: {{ .Values.acumosKongPGPassword }}
          - name: KONG_PG_HOST
            value: acumos-postgres.{{ .Values.namespace }}
          - name: KONG_PROXY_ACCESS_LOG
            value: "/dev/stdout"
          - name: KONG_ADMIN_ACCESS_LOG
            value: "/dev/stdout"
          - name: KONG_PROXY_ERROR_LOG
            value: "/dev/stderr"
          - name: KONG_ADMIN_ERROR_LOG
            value: "/dev/stderr"
        ports:
        - name: acumos-admin
          containerPort: {{ .Values.acumosKongAdminPort }}
          protocol: TCP
        - name: acumos-proxy
          containerPort: {{ .Values.acumosKongProxyPort }}
          protocol: TCP
        - name: acumos-kong-ssl
          containerPort: {{ .Values.acumosKongSslPort }}
          protocol: TCP
        - name: acumos-adm-ssl
          containerPort: {{ .Values.acumosKongAdmSslPort }}
          protocol: TCP

