# ===============LICENSE_START=======================================================
# Acumos Apache-2.0
# ===================================================================================
# Copyright (C) 2018-2019 AT&T Intellectual Property & Tech Mahindra. All rights reserved.
# ===================================================================================
# This Acumos software file is distributed by AT&T and Tech Mahindra
# under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ===============LICENSE_END=========================================================
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: logstash
  namespace: "{{ .Values.namespace }}"
  labels:
    app: logstash
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        releasetime: {{ $.Release.Time }}
      labels:
        app: logstash
    spec:
      containers:
      - name: logstash
        image: "{{ .Values.logstash.image.repository }}:{{ .Values.logstash.image.tag }}"
        imagePullPolicy: {{ .Values.logstash.image.pullPolicy | quote }}
        env:
        - name: ACUMOS_ELASTICSEARCH_PORT
          value: "9200"
        - name: ACUMOS_ELK_JDBC_DRIVER_LIBRARY
          value: "/usr/share/logstash/vendor/bundle/mariadb-java-client-2.1.0.jar"
        - name: ACUMOS_ELK_JDBC_DRIVER_CLASS
          value: "org.mariadb.jdbc.Driver"
        - name: ACUMOS_ELK_JDBC_CONNECTION_STRING
          value: "jdbc:mariadb://{{ .Values.databaseUrl }}.{{ .Values.namespace }}:{{ .Values.databasePortNo }}/{{ .Values.databaseName }}"
        - name: ACUMOS_ELK_JDBC_USERNAME
          value: "{{ .Values.databaseUserName }}"
        - name: ACUMOS_ELK_JDBC_PASSWORD
          value: "{{ .Values.databasePassword }}"
        ports:
        - containerPort: {{ .Values.logstash.image.port }}
        volumeMounts:
        - name: config
          mountPath: /usr/share/logstash/config/logstash.yml
          subPath: logstash.yml
          readOnly: true
        - name: pipeline
          mountPath: /usr/share/logstash/pipeline
          readOnly: true
        args:
        - -f
        - /usr/share/logstash/pipeline/logstash.conf
      restartPolicy: Always
      volumes:
        - name: config
          configMap:
            name: logstash
            items:
            - key: logstash.yml
              path: logstash.yml			
        - name: pipeline
          configMap:
            name: logstash
            items:
            - key: logstash.conf
              path: logstash.conf
      imagePullSecrets:
        - name: acumossecret
