apiVersion: v1
kind: Service
metadata:
  name: logstash-service
  namespace: "{{ .Values.namespace }}"
  labels:
    app: logstash
spec:
  ports:
    - name: logstash
      port: 5044
      targetPort: 5044
  selector:
    app: logstash
