version: '3.2'
# ===============LICENSE_START=======================================================
# Acumos Apache-2.0
# ===================================================================================
# Copyright (C) 2019 AT&T Intellectual Property & Tech Mahindra. All rights reserved.
# ===================================================================================
# This Acumos software file is distributed by AT&T and Tech Mahindra
# under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ===============LICENSE_END=========================================================
services:
  mlwb-home-webcomponent-service:
    image: ${MLWB_HOME_WEBCOMPONENT_IMAGE}
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ENVIRONMENT: "deploy"
      dashboardComponent: "http://mlwb-dashboard-webcomponent-service:9083"
      projectComponent: "http://mlwb-project-webcomponent-service:9084"
      projectCatalogComponent: "http://mlwb-project-catalog-webcomponent-service:9085"
      notebookComponent: "http://mlwb-notebook-webcomponent-service:9086"
      notebookCatalogComponent: "http://mlwb-notebook-catalog-webcomponent-service:9087"
      pipelineComponent: "http://mlwb-pipeline-webcomponent-service:9091"
      pipelineCatalogComponent: "http://mlwb-pipeline-catalog-webcomponent-service:9092"
      portalFEURL: "http://${ACUMOS_DOMAIN}"
      menuItems: '[
          {
          "title": "Dashboard",
          "icon": "fa fa-tachometer-alt",
          "link": "/pages/dashboard",
          "home": true
          },
          {
          "title": "Projects",
          "icon": "fa fa-project-diagram",
          "link": "/pages/projects/catalog"
          },
          {
          "title": "Notebooks",
          "icon": "fas fa-book-open",
          "link": "/pages/notebook/catalog"
          },
          {
          "title": "AcuCompose",
          "icon": "fas fa-crop-alt",
          "link": "/pages/acuCompose"
          }
        ]'
    ports:
      - ${MLWB_HOME_WEBCOMPONENT_PORT}:9082
    volumes:
      - type: bind
        source: /mnt/${ACUMOS_NAMESPACE}/logs
        target: /maven/logs
    restart: on-failure
