# ===============LICENSE_START=======================================================
# Acumos Apache-2.0
# ===================================================================================
# Copyright (C) 2017-2018 AT&T Intellectual Property & Tech Mahindra. All rights reserved.
# ===================================================================================
# This Acumos software file is distributed by AT&T and Tech Mahindra
# under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ===============LICENSE_END=========================================================

# What this is: kubernetes template for Acumos logging component services
# logstash, kibana, elasticsearch
apiVersion: v1
kind: Service
metadata:
  namespace: acumos
  name: elasticsearch-service
  labels:
    app: elasticsearch
spec:
  selector:
    app: elasticsearch
  type: NodePort
  ports:
  - nodePort: <ACUMOS_ELK_NODEPORT>
    port: <ACUMOS_ELK_ELASTICSEARCH_PORT>
    targetPort: 9200
---
apiVersion: v1
kind: Service
metadata:
  namespace: acumos
  name: logstash-service
  labels:
    app: logstash
spec:
  selector:
    app: logstash
  type: ClusterIP
  ports:
  - port: <ACUMOS_ELK_LOGSTASH_PORT>
    targetPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  namespace: acumos
  name: kibana-service
  labels:
    app: kibana
spec:
  selector:
    app: kibana
  type: NodePort
  ports:
  - nodePort: <ACUMOS_ELK_KIBANA_NODEPORT>
    port: <ACUMOS_ELK_KIBANA_PORT>
    targetPort: 5601
