apiVersion: v1
# ===============LICENSE_START=======================================================
# Acumos Apache-2.0
# ===================================================================================
# Copyright (C) 2017-2018 AT&T Intellectual Property & Tech Mahindra. All rights reserved.
# ===================================================================================
# This Acumos software file is distributed by AT&T and Tech Mahindra
# under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ===============LICENSE_END=========================================================

# What this is: kubernetes template for Acumos nexus service
# How to use:
# - Replace fields in <> with actual values (k8s does not support env variables)

kind: Service
metadata:
  namespace: acumos
  name: nexus-service
spec:
  selector:
    app: nexus
  type: NodePort
  ports:
  - name: nexus-api
    nodePort: <ACUMOS_NEXUS_API_PORT>
    port: 8081
    targetPort: 8081
  - name: nexus-model-maven
    nodePort: <ACUMOS_MAVEN_MODEL_PORT>
    port: 8001
    targetPort: 8001
  - name: nexus-model-docker
    nodePort: <ACUMOS_DOCKER_MODEL_PORT>
    port: 8002
    targetPort: 8002
  - name: nexus-platform-docker
    nodePort: <ACUMOS_DOCKER_PLATFORM_PORT>
    port: 8003
    targetPort: 8003

