apiVersion: apps/v1
# ===============LICENSE_START=======================================================
# Acumos Apache-2.0
# ===================================================================================
# Copyright (C) 2017-2018 AT&T Intellectual Property & Tech Mahindra. All rights reserved.
# ===================================================================================
# This Acumos software file is distributed by AT&T and Tech Mahindra
# under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ===============LICENSE_END=========================================================

# What this is: kubernetes template for Acumos docker-engine deployment
# How to use:
# - Replace fields in <> with actual values (k8s does not support env variables)

kind: Deployment
metadata:
  namespace: acumos
  name: docker
  labels:
    app: docker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: docker
    spec:
      restartPolicy: Always
      volumes:
      - name: docker-volume
        emptyDir: {}
      # Docker-commands-container
      containers:
      - name: docker-cmds
        image: docker:dind
        securityContext:
            privileged: true
        command: ['docker', 'run', '-p', '80:80', 'httpd:latest']
        env:
        - name: log_level
          value: "DEBUG"
        - name: DOCKER_HOST
          value: "tcp://0.0.0.0:<ACUMOS_DOCKER_API_PORT>"
        ports:
        - name: docker-api-port
          containerPort: <ACUMOS_DOCKER_API_PORT>
          protocol: TCP
      # Docker-Daemon-container
      - name: docker-daemon
        image: docker:dind
        securityContext:
            privileged: true
        env:
          - name: HTTP_PROXY
            value: "<HTTP_PROXY>"
          - name: HTTPS_PROXY
            value: "<HTTPS_PROXY>"
          - name: DIND_INSECURE_REGISTRIES
            value: "[\"0.0.0.0/0\"]"
          - name: DOCKER_OPTS
            value: '--insecure-registry=<ACUMOS_NEXUS_HOST>:<ACUMOS_DOCKER_MODEL_PORT>'
        args: ["$(DOCKER_OPTS)"]
        volumeMounts:
        - name: docker-volume
          mountPath: /var/lib/docker
      hostAliases:
      - ip: "<ACUMOS_HOST>"
        hostnames:
        - "<ACUMOS_DOMAIN>"
