# ===============LICENSE_START=======================================================
# Acumos Apache-2.0
# ===================================================================================
# Copyright (C) 2017-2018 AT&T Intellectual Property & Tech Mahindra. All rights reserved.
# ===================================================================================
# This Acumos software file is distributed by AT&T and Tech Mahindra
# under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ===============LICENSE_END=========================================================

# What this is: kubernetes template for Acumos logging component services
# logstash, kibana, elasticsearch
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: <ACUMOS_NAMESPACE>
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      imagePullSecrets:
      - name: acumos-registry
      containers:
      - name: elasticsearch
        image: <ELASTICSEARCH_IMAGE>
        env:
        - name: ES_JAVA_OPTS
          value: "-Xmx<ACUMOS_ELK_ES_JAVA_HEAP_MAX_SIZE> -Xms<ACUMOS_ELK_ES_JAVA_HEAP_MIN_SIZE>"
        - name: XPACK_SECURITY_ENABLED
          value: "false"
        - name: XPACK_MONITORING_ENABLED
          value: "false"
        ports:
        - containerPort: 9200
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
          name: config
        - mountPath: /usr/share/elasticsearch/data
          name: esdata
      restartPolicy: Always
      volumes:
      - name: config
        hostPath:
          path: /var/acumos/elasticsearch/config/elasticsearch.yml
      - name: esdata
        hostPath:
          path: /var/acumos/esdata
      hostAliases:
      - ip: "<ACUMOS_HOST>"
        hostnames:
        - "<ACUMOS_DOMAIN>"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: <ACUMOS_NAMESPACE>
  name: logstash
  labels:
    app: logstash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: logstash
    spec:
      imagePullSecrets:
      - name: acumos-registry
      containers:
      - name: logstash
        image: <LOGSTASH_IMAGE>
        env:
        - name: ES_JAVA_OPTS
          value: "-Xmx<ACUMOS_ELK_LS_JAVA_HEAP_MAX_SIZE> -Xms<ACUMOS_ELK_LS_JAVA_HEAP_MIN_SIZE>"
        - name: ACUMOS_ELK_JDBC_DRIVER_LIBRARY
          value: "/usr/share/logstash/vendor/bundle/mariadb-java-client-2.1.0.jar"
        - name: ACUMOS_ELK_JDBC_DRIVER_CLASS
          value: "org.mariadb.jdbc.Driver"
        - name: ACUMOS_ELK_JDBC_CONNECTION_STRING
          value: "jdbc:mariadb://<ACUMOS_MARIADB_HOST>:<ACUMOS_MARIADB_PORT>/<ACUMOS_CDS_DB>"
        - name: ACUMOS_ELK_JDBC_USERNAME
          value: "acumos_opr"
        - name: ACUMOS_ELK_JDBC_PASSWORD
          value: "<ACUMOS_MARIADB_USER_PASSWORD>"
        ports:
        - containerPort: 5000
        volumeMounts:
        - mountPath: /usr/share/logstash/config
          name: config
        - mountPath: /usr/share/logstash/pipeline
          name: pipeline
      restartPolicy: Always
      volumes:
      - name: config
        hostPath:
          path: /var/acumos/logstash/config
      - name: pipeline
        hostPath:
          path: /var/acumos/logstash/pipeline
      hostAliases:
      - ip: "<ACUMOS_HOST>"
        hostnames:
        - "<ACUMOS_DOMAIN>"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: <ACUMOS_NAMESPACE>
  name: kibana
  labels:
    app: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: kibana
    spec:
      imagePullSecrets:
      - name: acumos-registry
      containers:
      - name: kibana
        image: <KIBANA_IMAGE>
        ports:
        - containerPort: 5601
        volumeMounts:
        - mountPath: /usr/share/kibana/config
          name: config
      restartPolicy: Always
      volumes:
      - name: config
        hostPath:
          path: /var/acumos/kibana/config
      hostAliases:
      - ip: "<ACUMOS_HOST>"
        hostnames:
        - "<ACUMOS_DOMAIN>"
