#
#============LICENSE_START=======================================================
# 
#================================================================================
# Copyright (C) 2020 AT&T
#================================================================================
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ============LICENSE_END=========================================================

apiVersion: apps/v1
kind: Deployment
metadata:
 name: {{.Values.global.microserviceGeneration.podName}}
 namespace: "{{ .Values.global.namespace }}"
 labels:
   app: {{.Values.global.microserviceGeneration.name}}
spec:
 selector:
   matchLabels:
     app: {{.Values.global.microserviceGeneration.name}} 
 replicas: 1
 revisionHistoryLimit: 10
 template:
   metadata:
     labels:
       app: {{.Values.global.microserviceGeneration.name}}
   spec:
     containers:
       - name: microservice-generation
         image: {{ .Values.global.nexus3ReleaseRegistryLf }}/acumos/{{ .Values.global.acumosMicroServiceGenerationImage }}
         ports:
           - containerPort: {{ .Values.global.acumosMicroServiceGenerationPort }}
         env:
           - name: SPRING_APPLICATION_JSON
             value: '{
                   "server":{
                     "port": {{ .Values.global.acumosMicroServiceGenerationPort }},
                     "servlet": {
                         "context-path": "/microservice-generation"
                               }
                   },
                   "docker": {
                     "host": "{{ .Values.global.acumosDockerHost }}.{{ .Values.global.namespace }}",
                     "port": "{{ .Values.global.acumosDockerPort }}",
                     "config": "/docker_host/.docker",
                     "registry" :{"url": "http://{{ .Values.global.acumosNexusService }}.{{ .Values.global.namespace }}:{{ .Values.global.acumosNexusPort }}/",
                     "username" : "{{ .Values.global.acumosNexusUsername }}",
                     "password" : "{{ .Values.global.acumosNexusPassword }}", 
                     "email": "{{ .Values.global.acumosDockerRegistryEmail }}"},
                     "tls": {
                       "verify": "false"
                     },
                     "api": {
                       "version": "1.23"
                     },
                     "imagetag": {
                       "prefix": "{{ .Values.global.acumosNexusService }}.{{ .Values.global.namespace }}:{{ .Values.global.acumosNexusPort }}"
                     },
                     "max_total_connections": "1",
                     "max_per_route_connections": "1"
                   },
                   "http_proxy": "http://{{ .Values.global.acumosProxy }}.{{ .Values.global.namespace }}:{{ .Values.global.acumosProxyPort }}",
                   "nexus": {
                            "nexusEndPointURL": "http://{{ .Values.global.acumosNexusService }}.{{ .Values.global.namespace }}:{{ .Values.global.acumosNexusEndpointPort }}/repository/acumos-k8-models-maven/",
                            "nexusUserName": "{{ .Values.global.acumosNexusUsername }}",
                            "nexusPassword": "{{ .Values.global.acumosNexusPassword }}",
                            "nexusproxy": "",
                            "nexusGroupId": "com.artifact" 
                           },
                   "cmndatasvc": {
                                "cmnDataSvcEndPoinURL": "http://{{.Values.global.cds.svcName}}.{{ .Values.global.namespace }}:{{ .Values.global.acumosCommonDataSvcPort }}/ccds",
                                "cmnDataSvcUser": "{{ .Values.global.acumosCdsUser }}",
                                "cmnDataSvcPwd": "{{ .Values.global.acumosCdsPassword }}" 
                               },
                   "mktPlace": {
                     "mktPlaceEndPointURL": "http://{{.Values.global.portal.portalBe.svcName}}.{{ .Values.global.namespace }}:{{ .Values.global.acumosPortalBePort }}"
                   },
                   "microService": {
                     "microServiceEndPointURL": "http://{{.Values.global.microserviceGeneration.svcName}}.{{ .Values.global.namespace }}:{{ .Values.global.acumosMicroServiceGenerationPort }}/microservice-generation",
                     "microServiceAsyncFlag": "true"
                   },
                   "requirements": {
                     "extraIndexURL": "",
                     "trustedHost": ""
                   },
                   "security" : {
                     "verificationEnableFlag" : "{{ .Values.global.acumosSVscan }}",
                     "verificationApiUrl" : " http://acumos.{{ .Values.global.namespace }}:{{ .Values.global.acumosSecurityVerificationPort }}"
                   },
                   "modelrunnerVersion" : {
                     "javaSpark" : "1.0.2",
                     "H2O" : "2.2.3"
                   },
                   "base_image": {
                     "rimage": "{{ .Values.global.nexus3ReleaseRegistryLf }}/{{ .Values.global.acumosmicroserviceGenerationBaseRImage }}",
                     "dockerusername": "{{ .Values.global.acumosDockerUsername }}",
                     "dockerpassword": "{{ .Values.global.acumosDockerPassword }}"
                   },
                   "spring": {
                     "servlet": {
                       "multipart": {
                          "max-file-size": "-1",
                          "max-request-size": "-1"
                       }
                     }
                   }
                 }'
         volumeMounts:
           - mountPath: /maven/logs
             name: acumos-microservice-generation-logs
       - name: filebeat
         image: {{ .Values.global.nexus3ReleaseRegistryLf }}/acumos/{{ .Values.global.acumosFilebeatImage }}
         ports:
           - containerPort: {{ .Values.global.acumosFilebeatPort }}
         env:
           - name: LOGSTASH_HOST
             value: {{ .Values.global.acumosLogstashHost }}.{{ .Values.global.namespace }}
           - name: LOGSTASH_PORT
             value: "{{ .Values.global.acumosLogstashPort }}"
         volumeMounts:
           - mountPath: /filebeat-logs
             name: acumos-microservice-generation-logs
     volumes:
       - name: acumos-microservice-generation-logs  
         emptyDir: {}
     imagePullSecrets:
       - name: acumossecret
