{{- /*
* ===============LICENSE_START=======================================================
* Acumos Apache-2.0
* ===================================================================================
* Copyright (C) 2019-2020  Nordix Foundation & AT&T Intellectual Property
* ===================================================================================
* This Acumos software file is distributed by Nordix Foundation & AT&T
* under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* This file is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
* ===============LICENSE_END=========================================================
*/ -}}

{{- /*
Lum database setup scripts. Provided as a config map to portgresql
*/ -}}

apiVersion: v1

# Database table setup and inserting default data into table
kind: ConfigMap
metadata:
  # Not using relase due to issue with this name must be passed in values.yaml
  # We are not including the user and db creation because the helm chart from postgresql
  # is handling lumdb creation and user creation. password uses k8 secrets.
  name: database-table-table-creation
data:
  {{- (.Files.Glob "files/docker-entrypoint-initdb.d/*").AsConfig | nindent 2 }}