version: '2'
# ===============LICENSE_START=======================================================
# Acumos Apache-2.0
# ===================================================================================
# Copyright (C) 2017-2018 AT&T Intellectual Property & Tech Mahindra. All rights reserved.
# ===================================================================================
# This Acumos software file is distributed by AT&T and Tech Mahindra
# under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ===============LICENSE_END=========================================================

# docker-compose for federation-gateway
# TODO: remove ports: for services that do not need external exposure
# TODO: remove or parameterize all credentials
# TODO: scrub all attributes for current need
services:
   federation-gateway:
       image: ${FEDERATION_IMAGE}
       environment:
           SPRING_APPLICATION_JSON: "{
               \"federation\" : {
                    \"instance\" : \"gateway\",
                    \"instance.name\": \"aio\",
                    \"operator\" : \"bc0f5023-79c0-4a99-a7a3-46c83f9ef806\",
                    \"address\" : \"0.0.0.0\",
                    \"server\" : {
                       \"port\" : ${ACUMOS_FEDERATION_PORT}
                    },
                    \"ssl\" : {
                       \"key-store\" : \"/app/certs/acumos_aio.p12\",
                       \"key-store-password\" : \"${ACUMOS_KEYPASS}\",
                       \"key-store-type\" : \"PKCS12\",
                       \"key-password\" : \"${ACUMOS_KEYPASS}\",
                       \"trust-store\" : \"/app/certs/acumosTrustStore.jks\",
                       \"trust-store-password\" : \"${ACUMOS_KEYPASS}\"
                    }
                },
                \"local\" : {
                   \"address\": \"0.0.0.0\",
                   \"server\" : {
                      \"port\" : ${ACUMOS_FEDERATION_LOCAL_PORT}
                   },
                   \"ssl\" : {
                      \"key-store\" : \"/app/certs/acumos_aio.p12\",
                      \"key-store-password\" : \"${ACUMOS_KEYPASS}\",
                      \"key-store-type\" : \"PKCS12\",
                      \"key-password\" : \"${ACUMOS_KEYPASS}\",
                      \"trust-store\" : \"/app/certs/acumosTrustStore.jks\",
                      \"trust-store-password\" : \"${ACUMOS_KEYPASS}\"
                   }
                },
                \"nexus\": {
                   \"nexusendpointurl\": \"http://nexus:${ACUMOS_NEXUS_API_PORT}/repository/acumos_model_maven/\",
                   \"nexusproxy\": \"\",
                   \"nexuspassword\": \"${ACUMOS_RW_USER_PASSWORD}\",
                   \"nexususername\": \"acumos_rw\",
                   \"nexusgroupid\": \"com.artifact\"
                },
                \"peer\": {
                    \"jobchecker\": {
                        \"interval\": 300
                    }
                },
                \"cdms\" : {
                  \"client\" : {
                     \"url\": \"http://common-data-svc:${ACUMOS_CDS_PORT}/ccds\",
                     \"username\": \"${ACUMOS_CDS_USER}\",
                     \"password\": \"${ACUMOS_CDS_PASSWORD}\"
                  }
                }
           }"
       expose:
           - ${ACUMOS_FEDERATION_PORT}
           - ${ACUMOS_FEDERATION_LOCAL_PORT}
       ports:
           - ${ACUMOS_FEDERATION_PORT}:${ACUMOS_FEDERATION_PORT}
           - ${ACUMOS_FEDERATION_LOCAL_PORT}:${ACUMOS_FEDERATION_LOCAL_PORT}
       links:
           - common-data-svc
       depends_on:
           - common-data-svc
       volumes:
           - acumos-logs:/maven/logs
           - /home/ubuntu/certs:/app/certs
       logging:
           driver: json-file

