version: '2'
# ===============LICENSE_START=======================================================
# Acumos Apache-2.0
# ===================================================================================
# Copyright (C) 2017-2018 AT&T Intellectual Property & Tech Mahindra. All rights reserved.
# ===================================================================================
# This Acumos software file is distributed by AT&T and Tech Mahindra
# under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ===============LICENSE_END=========================================================

# docker-compose for nexus
# Ports are exposed since docker build server needs access to 
# TODO: remove or parameterize all credentials
# TODO: scrub all attributes for current need
services:
   nexus:
       image: sonatype/nexus3:3.9.0
       ports:
           - ${ACUMOS_NEXUS_API_PORT}:8081
           - ${ACUMOS_MAVEN_MODEL_PORT}:${ACUMOS_MAVEN_MODEL_PORT}
           - ${ACUMOS_DOCKER_MODEL_PORT}:${ACUMOS_DOCKER_MODEL_PORT}
           - ${ACUMOS_DOCKER_PLATFORM_PORT}:${ACUMOS_DOCKER_PLATFORM_PORT}
       volumes:
           - acumos-logs:/maven/logs
       logging:
           driver: json-file

