# ===============LICENSE_START=======================================================
# Acumos Apache-2.0
# ===================================================================================
# Copyright (C) 2018-2020 AT&T Intellectual Property & Tech Mahindra. All rights reserved.
# ===================================================================================
# This Acumos software file is distributed by AT&T and Tech Mahindra
# under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ===============LICENSE_END=========================================================

logLevel: INFO

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

pushSelfRequestEnable: "true"
publicationEnable: "true"
emailService: ""
casEnable: "false"
verifyAccount: "false"
tokenExpTime: 24

#portal-ui
dsMenu: "{\\\"workbenchActive\\\":true,\\\"acucomposeActive\\\":true,\\\"blocks\\\":[{\\\"active\\\":true,\\\"title\\\":\\\"AT&T Test 2\\\",\\\"description\\\":\\\"This another new test of the DS TILE THAT IS CONFIGURABLE VIA YML.\\\",\\\"url\\\":\\\"http://att.com\\\",\\\"imagePath\\\":\\\"/images/sidebar-icons/lfai-landscape-icon-color.png\\\"},{\\\"active\\\":true,\\\"title\\\":\\\"AT&T Test\\\",\\\"description\\\":\\\"This a new test of the DS TILE THAT IS CONFIGURABLE VIA YML.\\\",\\\"url\\\":\\\"http://att.com\\\",\\\"imagePath\\\":\\\"/images/sidebar-icons/AI_Ethics.png\\\"}]}"
sideMenu: "[{\\\"name\\\" : \\\"ML Learning Path\\\", \\\"url\\\" : \\\"\\\", \\\"imagePath\\\" : \\\"/images/sidebar-icons/ML_learning_path_selected.png\\\" }]"

#Storage
storageAccessModes: ReadWriteMany
storageClassName: 
storageSize: "5Gi"