# ===============LICENSE_START=======================================================
# Acumos Apache-2.0
# ===================================================================================
# Copyright (C) 2018-2019 AT&T Intellectual Property & Tech Mahindra. All rights reserved.
# ===================================================================================
# This Acumos software file is distributed by AT&T and Tech Mahindra
# under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ===============LICENSE_END=========================================================
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: acumos
  name: acumos-mysql
  namespace: "{{ .Values.global.namespace }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: acumos
      tier: mysql
  template:
    metadata:
      labels:
        app: acumos
        tier: mysql
    spec:
      containers:
        - name: mysql
          image: mariadb
          ports:
            - containerPort: {{ .Values.global.acumosCdsDbPort }}
              name: mysql
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "{{ .Values.global.acumosCdsDbRootPassword }}"
          volumeMounts:
            - name: mariadb-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mariadb-persistent-storage
          persistentVolumeClaim:
            claimName: acumos-mariadb-volumeclaim
