#
#============LICENSE_START=======================================================
# Acumos Apache-2.0
#================================================================================
# Copyright (C) 2020 AT&T Intellectual Property & Tech Mahindra. All rights reserved.
#================================================================================
# This Acumos software file is distributed by AT&T and Tech Mahindra
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ============LICENSE_END=========================================================
dependencies:
  - name: couchdb
  version: 3.2.0
  repository: https://github.com/apache/couchdb-helm/tree/master/couchdb
  condition: globals.couchdb.enabled
  tags:
    - database
    - couchdb-chart
- name: jupyterhub
  version: 0.8.2
  repository: https://jupyterhub.github.io/helm-chart/
  condition: globals.jupyterhub.enabled
  tags:
    - notebook
    - jupyterhub-chart
- name: nifi
  version: 0.3.3
  repository: https://cetic.github.io/helm-charts
  condition: globals.nifi.enabled
  tags:
    - datarouter
    - nifi-chart
  - name: project-service
    repository: 'file://charts/project-service'
    version: ~2.x-0
  - name: notebook-service
    repository: 'file://charts/notebook-service'
    version: ~2.x-0
  - name: pipeline-service
    repository: 'file://charts/pipeline-service'
    version: ~2.x-0
  - name: model-service
    repository: 'file://charts/model-service'
    version: ~2.x-0
  - name: predictor-service
    repository: 'file://charts/predictor-service'
    version: ~2.x-0
  - name: dashboard-webcomponent
    repository: 'file://charts/dashboard-webcomponent'
    version: ~2.x-0
  - name: home-webcomponent
    repository: 'file://charts/home-webcomponent'
    version: ~2.x-0
  - name: notebook-catalog-webcomponent
    repository: 'file://charts/notebook-catalog-webcomponent'
    version: ~2.x-0
  - name: notebook-webcomponent
    repository: 'file://charts/notebook-webcomponent'
    version: ~2.x-0
  - name: pipeline-catalog-webcomponent
    repository: 'file://charts/pipeline-catalog-webcomponent'
    version: ~2.x-0
  - name: pipeline-webcomponent
    repository: 'file://charts/pipeline-webcomponent'
    version: ~2.x-0
  - name: project-catalog-webcomponent
    repository: 'file://charts/project-catalog-webcomponent'
    version: ~2.x-0
  - name: project-webcomponent
    repository: 'file://charts/project-webcomponent'
    version: ~2.x-0
