# ===============LICENSE_START=======================================================
# Acumos Apache-2.0
# ===================================================================================
# Copyright (C) 2019 AT&T Intellectual Property & Tech Mahindra. All rights reserved.
# ===================================================================================
# This Acumos software file is distributed by AT&T and Tech Mahindra
# under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ===============LICENSE_END=========================================================
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
appVersion: "1.0.0"

namespace: "acumos-test"
clusterName: "k8-cluster-elk"

elasticsearch:
  image:
    repository: "nexus3.acumos.org:10004/acumos-elasticsearch"
    tag: "2.0.7"
    pullPolicy: "IfNotPresent"

  persistence:
    enabled: true
    pvcName: "elasticsearch-data"
    size: "10Gi"

  resources:
    limits:
      cpu: "750m"
      memory: "6Gi"
    requests:
      cpu: "750m"
      memory: "4Gi"

  nodeAffinity: {}
  nodeSelector: {}
  tolerations: []

logstash:
  image:
    repository: "nexus3.acumos.org:10004/acumos-logstash"
    tag: "2.0.7"
    pullPolicy: "IfNotPresent"

kibana:
  image:
    repository: "nexus3.acumos.org:10004/acumos-kibana"
    tag: "2.0.7"
    pullPolicy: "IfNotPresent"

  tls:
    crt: 
    key: 
  
  ingress:
    enabled: false
    host: ""
    whitelist:
      enabled: false
      ranges: ""
    letsencrypt:
      enabled: false