# ===============LICENSE_START=======================================================
# Acumos Apache-2.0
# ===================================================================================
# Copyright (C) 2018-2019 AT&T Intellectual Property & Tech Mahindra. All rights reserved.
# ===================================================================================
# This Acumos software file is distributed by AT&T and Tech Mahindra
# under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ===============LICENSE_END=========================================================
apiVersion: v1
kind: Service
metadata:
  name: acumos-postgres
  namespace: "{{ .Values.global.namespace }}"
spec:
  ports:
  - name: pgql
    port: {{ .Values.global.acumosKongPostgresPort }}
    targetPort: {{ .Values.global.acumosKongPostgresPort }}
    protocol: TCP
  selector:
    app: acumos-postgres

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: acumos-postgres
  namespace: "{{ .Values.global.namespace }}"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: acumos-postgres
    spec:
      containers:
        - name: acumos-postgres
          image: postgres:9.6
          env:
            - name: POSTGRES_USER
              value: "{{ .Values.global.acumosKongPostgresUser }}"
            - name: POSTGRES_PASSWORD
              value: "{{ .Values.global.acumosKongPostgresPassword }}"
            - name: POSTGRES_DB
              value: "{{ .Values.global.acumosKongPostgresDB }}"
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - containerPort: {{ .Values.global.acumosKongPostgresPort }}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: pg-data
      volumes:
        - name: pg-data
          emptyDir: {}
