# Default values for elasticsearch.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
appVersion: "1.0.0"

# Consult global_values.yaml file for Kong template values



