{{- /*
* ===============LICENSE_START=======================================================
* Acumos Apache-2.0
* ===================================================================================
* Copyright (C) 2019-2020  Nordix Foundation & AT&T Intellectual Property
* ===================================================================================
* This Acumos software file is distributed by Nordix Foundation & AT&T
* under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* This file is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
* ===============LICENSE_END=========================================================
*/ -}}
dependencies:
- name: postgresql
  version: 6.3.11
  repository: https://kubernetes-charts.storage.googleapis.com
  condition: globals.postgresql.enabled
  tags:
    - database
    - postgresql-chart